name: 'Delete comments'
author: 'Marco De Toma'
description: 'Delete issue or pull request comment'
inputs:
  token:
    required: true
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    required: true
    description: 'The full name of the repository containing the issue or pull request.'
    default: ${{ github.repository }}
  comment-id:
    required: true
    description: 'The comment id to delete.'
outputs:
  done:
    description: 'true when the comment is found and deleted, false otherwise'

branding:
  color: blue
  icon: delete

runs:
  using: 'node16'
  main: 'dist/index.js'
