name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: install
        run: |
          npm install

      - name: build
        run: |
          npm run build

      - name: format-check
        run: |
          npm run format-check

      - name: lint
        run: |
          npm run lint

      - name: package
        run: |
          npm run package

